import React from 'react';

export const BrainIcon = () => <i className="fas fa-brain text-xl"></i>;
export const SettingsIcon = () => <i className="fas fa-cog text-xl"></i>;
export const ListIcon = () => <i className="fas fa-list-ol text-xl"></i>;
export const CheckIcon = () => <i className="fas fa-check"></i>;
export const PlayIcon = () => <i className="fas fa-play"></i>;
export const CpuIcon = () => <i className="fas fa-microchip"></i>;
export const SparklesIcon = () => <i className="fas fa-magic"></i>;
export const EyeSlashIcon = () => <i className="fas fa-eye-slash"></i>;
export const PlusIcon = () => <i className="fas fa-plus"></i>;
export const TrashIcon = () => <i className="fas fa-trash"></i>;
export const DownloadIcon = () => <i className="fas fa-download"></i>;
export const UploadIcon = () => <i className="fas fa-upload"></i>;
export const CopyIcon = () => <i className="fas fa-copy"></i>;
export const EditIcon = () => <i className="fas fa-pencil-alt"></i>;
export const RefreshIcon = () => <i className="fas fa-undo"></i>;
export const DumbbellIcon = () => <i className="fas fa-dumbbell text-xl"></i>;
export const ArrowRightIcon = () => <i className="fas fa-arrow-right"></i>;
export const FireIcon = () => <i className="fas fa-fire"></i>;
