export const TRANSLATIONS = {
  fr: {
    navHome: "Accueil",
    navAbout: "À propos",
    navMethod: "Méthode",
    navProjects: "Projets",
    heroGreeting: "Bonjour, je suis ",
    heroSub: "Étudiant en informatique, passionné de systèmes complexes, d'escalade et de design créatif.",
    heroBtn: "Voir mes projets",
    aboutTitle: "À propos de moi",
    aboutP1: "Je suis étudiant en troisième année en informatique (régime coopératif) à l'Université d'Ottawa, et je complète actuellement une mineure en psychologie. Quand je ne suis pas derrière mon écran, vous me trouverez généralement en train de faire de l'escalade de bloc (bouldering) ou de passer du temps en plein air avec mon chien.",
    aboutP2: "J'adore acquérir de nouvelles compétences et travailler de mes mains, ce qui m'a récemment amené à explorer la couture, les arts du papier et la création de motifs personnalisés pour découpe de vinyle.",
    aboutP3: "J'ai également une solide base en design graphique et en arts visuels (j'ai d'ailleurs remporté deux fois le concours de la page couverture de l'album des finissants de mon école secondaire). J'aime allier logique et créativité pour concevoir des systèmes à la fois hautement fonctionnels et esthétiques.",
    skillsTitle: "Compétences",
    skillsCyber: "Cybersécurité",
    skillsServers: "Serveurs",
    skillsPsych: "Psychologie",
    skillsDesign: "Design Visuel",
    methodTitle: "Comment je travaille",
    methodP1: "Bien que mon expérience soit profondément ancrée dans les systèmes backend et le design graphique, j'élargis actuellement mes compétences en conception d'interfaces utilisateurs (UI).",
    methodP2: "Je suis le cours SEG3525 à l'Université d'Ottawa, où j'apprends les éléments fondamentaux de la conception centrée sur l'utilisateur. Tout au long de ce semestre, j'appliquerai les principes de ressources de l'industrie comme NN/g.",
    methodNote: "* Plus tard dans le semestre, j'ajouterai les différents concepts utilisés pour démontrer mon expertise (conception centrée sur l'utilisateur, évaluation heuristique, etc.) et mon processus de conception.",
    methodP3: "J'ai aussi effectué deux stages coopératifs chez Adaptron Inc., une entreprise spécialisée dans le développement de nouvelles méthodes de création d'intelligence artificielle.",
    step1Title: "1. Remue-méninges physique",
    step1Text: "J'utilise des supports physiques (tableau blanc, papier) pour réfléchir, esquisser des idées et conceptualiser une solution en prenant du recul.",
    step2Title: "2. Raffinement et documentation",
    step2Text: "Je passe à un document numérique pour peaufiner mon plan, sélectionner la solution idéale, et définir les modèles de conception.",
    step3Title: "3. Modélisation (Diagrammes)",
    step3Text: "Au besoin, je crée des diagrammes détaillés pour illustrer les interactions au sein du système.",
    step4Title: "4. Implémentation",
    step4Text: "Ce n'est qu'une fois l'architecture solidement planifiée que je commence à programmer.",
    casesTitle: "Études de cas",
    casesSub: "Voici les quatre interfaces que je développerai tout au long de ce semestre.",
    project1Title: "Hôpital vétérinaire",
    project1Text: "Projet de conception UI/UX axé sur une plateforme de réservation de services pour animaux.",
    project2Title: "Jeu de mémoire visuelle",
    project2Text: "Un jeu interactif sur navigateur conçu pour tester le rappel cognitif et l'engagement.",
    project3Title: "Boutique d'arts",
    project3Text: "Prototype de boutique en ligne pour naviguer et acheter des créations artisanales.",
    project4Title: "Tableau de bord d'escalade",
    project4Text: "Visualisation de données pour aider les grimpeurs à suivre leurs cotations et séances.",
    comingSoon: "À venir",
    footerCourse: "Créé pour le cours SEG3525"
  },
  en: {
    navHome: "Home",
    navAbout: "About",
    navMethod: "Method",
    navProjects: "Projects",
    heroGreeting: "Hello, I am ",
    heroSub: "Computer Science student, passionate about complex systems, bouldering, and creative design.",
    heroBtn: "View my projects",
    aboutTitle: "About me",
    aboutP1: "I am a third-year Computer Science student (co-op) at the University of Ottawa, currently completing a minor in Psychology. When I'm not behind a screen, you'll usually find me bouldering or spending time outdoors with my dog.",
    aboutP2: "I love learning new skills and working with my hands, which recently led me to explore sewing, papercrafts, and creating custom vinyl cutting patterns.",
    aboutP3: "I also have a strong foundation in graphic design and visual arts (I even won my high school yearbook cover contest twice). I enjoy combining logic and creativity to design systems that are both highly functional and aesthetically pleasing.",
    skillsTitle: "Skills",
    skillsCyber: "Cybersecurity",
    skillsServers: "Servers",
    skillsPsych: "Psychology",
    skillsDesign: "Visual Design",
    methodTitle: "How I work",
    methodP1: "Although my background is deeply rooted in backend systems and graphic design, I am currently expanding my skills in user interface (UI) design.",
    methodP2: "I am taking the SEG3525 course at the University of Ottawa, where I am learning the fundamentals of user-centered design. Throughout this semester, I will apply principles from industry resources like NN/g.",
    methodNote: "* Later in the semester, I will add the different concepts used to demonstrate my expertise (user-centered design, heuristic evaluation, etc.) and my design process.",
    methodP3: "I also completed two co-op terms at Adaptron Inc., a company developing innovative methods for creating artificial intelligence.",
    step1Title: "1. Physical Brainstorming",
    step1Text: "I use physical mediums (whiteboard, paper) to brainstorm, sketch ideas, and conceptualize a solution while stepping back.",
    step2Title: "2. Refinement and Documentation",
    step2Text: "I switch to a digital document to refine my plan, select the ideal solution, and define design patterns.",
    step3Title: "3. Modeling (Diagrams)",
    step3Text: "If needed, I create detailed diagrams to illustrate the interactions within the system.",
    step4Title: "4. Implementation",
    step4Text: "I only start programming once the architecture is solidly planned.",
    casesTitle: "Case Studies",
    casesSub: "Here are the four interfaces I will develop throughout this semester.",
    project1Title: "Veterinary Hospital",
    project1Text: "UI/UX design project focused on a service booking platform for animals.",
    project2Title: "Visual Memory Game",
    project2Text: "An interactive browser game designed to test cognitive recall and engagement.",
    project3Title: "Art Shop",
    project3Text: "Online store prototype for browsing and purchasing handcrafted creations.",
    project4Title: "Climbing Dashboard",
    project4Text: "Data visualization to help climbers track their grades and sessions.",
    comingSoon: "Coming Soon",
    footerCourse: "Created for the SEG3525 course"
  }
};
